// api/_lib/demos-core.mjs: pure zip handling for demo uploads (no network, no env).
//
// Kept separate from api/demos.mjs so it can be unit tested with node:test.
// Vercel does not turn files under an underscore folder into functions.
//
// Two kinds of upload are supported:
//   source  has package.json. Vercel builds it with --base=/<slug>/.
//   built   a Vite dist folder (index.html at the root). Deployed as is, after
//           rewriting root-absolute paths ("/assets/...") to "/<slug>/assets/...".

import { unzipSync } from 'fflate';
import { createHash } from 'node:crypto';

export const SLUG_RE = /^[a-z0-9][a-z0-9-]{0,39}$/;
const RESERVED = new Set(['api', 'admin', 'assets', '_next', '_vercel', 'favicon.ico', 'robots.txt', 'og-image.png', 'index', 'index.html', 'fonts', 'logo-mark.webp', 'favicon-32.png', 'apple-touch-icon.png']);

export const LIMITS = {
  maxFiles: 5000,
  maxUncompressedBytes: 100 * 1024 * 1024,
};

// Never deployed, whatever the kind.
const JUNK = [/^__MACOSX\//, /(^|\/)\.DS_Store$/, /(^|\/)Thumbs\.db$/, /^\.git\//, /^\.vercel\//];
// Regenerated by Vercel's build, so dropped from source uploads only.
const SOURCE_ONLY_JUNK = [/^node_modules\//, /^dist\//];
const ENV_FILES = ['.env', '.env.production', '.env.local', '.env.production.local']; // lowest to highest precedence
const TEXT_EXT = /\.(html?|m?js|css|json|webmanifest|svg|xml|txt)$/i;

export class DemoError extends Error {}

export function validateSlug(slug) {
  if (typeof slug !== 'string' || !SLUG_RE.test(slug)) {
    return 'Use 1 to 40 lowercase letters, numbers, or hyphens, starting with a letter or number.';
  }
  if (RESERVED.has(slug)) return `"${slug}" is reserved. Pick another slug.`;
  return null;
}

function isUnsafePath(name) {
  return (
    name.startsWith('/') ||
    name.includes('\\') ||
    /^[a-zA-Z]:/.test(name) ||
    name.split('/').some((seg) => seg === '..')
  );
}

// Unzip with limits enforced before anything is decompressed.
export function readZip(bytes) {
  let count = 0;
  let total = 0;
  let raw;
  try {
    raw = unzipSync(bytes, {
      filter(file) {
        if (file.name.endsWith('/')) return false;
        if (isUnsafePath(file.name)) throw new DemoError(`Unsafe path in zip: ${file.name}`);
        if (JUNK.some((re) => re.test(file.name))) return false;
        count += 1;
        total += file.originalSize;
        if (count > LIMITS.maxFiles) throw new DemoError(`Too many files (limit ${LIMITS.maxFiles}). Leave node_modules out of the zip.`);
        if (total > LIMITS.maxUncompressedBytes) throw new DemoError('Zip is too large once unpacked (limit 100 MB). Leave node_modules out of the zip.');
        return true;
      },
    });
  } catch (error) {
    if (error instanceof DemoError) throw error;
    throw new DemoError('That file could not be read as a zip.');
  }
  return new Map(Object.entries(raw));
}

// Zips made by Finder or the Files app wrap everything in one folder, sometimes two
// (e.g. "my-site/dist/"). Strip wrappers until the root has more than one entry.
export function stripWrappers(files) {
  let current = files;
  for (;;) {
    const tops = new Set([...current.keys()].map((p) => p.split('/')[0]));
    const [only] = tops;
    const wrapped = tops.size === 1 && [...current.keys()].every((p) => p.startsWith(`${only}/`));
    if (!wrapped) return current;
    const next = new Map();
    for (const [path, data] of current) next.set(path.slice(only.length + 1), data);
    current = next;
  }
}

export function detectKind(files) {
  if (files.has('package.json')) return 'source';
  if (files.has('index.html')) return 'built';
  throw new DemoError('No package.json or index.html at the top of the zip. Zip the project folder, or its built dist folder.');
}

const decoder = new TextDecoder();
const encoder = new TextEncoder();
const text = (data) => decoder.decode(data);

export function parseEnv(source) {
  const out = {};
  for (const line of source.split(/\r?\n/)) {
    const match = /^\s*(?:export\s+)?([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)?\s*$/.exec(line);
    if (!match) continue;
    let value = (match[2] ?? '').trim();
    if (/^(["']).*\1$/.test(value)) value = value.slice(1, -1);
    else value = value.replace(/\s+#.*$/, '');
    out[match[1]] = value;
  }
  return out;
}

// VITE_* values from .env files in a source zip. Other keys are ignored on purpose:
// only VITE_* ends up in a static build, and anything else may be a real secret.
export function collectEnv(files) {
  const env = {};
  for (const name of ENV_FILES) {
    if (!files.has(name)) continue;
    for (const [key, value] of Object.entries(parseEnv(text(files.get(name))))) {
      if (key.startsWith('VITE_')) env[key] = value;
    }
  }
  return env;
}

export function buildCommandFor(pkg, slug) {
  const script = pkg?.scripts?.build;
  if (typeof script === 'string' && /vite build[^&|;]*$/.test(script.trim())) {
    return { command: `npm run build -- --base=/${slug}/`, warning: null };
  }
  return {
    command: `npx vite build --base=/${slug}/`,
    warning: 'The build script does not end with "vite build", so Vite is run directly. Any extra build steps are skipped.',
  };
}

function sourceWarnings(files) {
  const warnings = [];
  const pkg = JSON.parse(text(files.get('package.json')));
  const deps = { ...pkg.dependencies, ...pkg.devDependencies };

  if (deps['vite-plugin-pwa']) {
    warnings.push('Uses vite-plugin-pwa. A service worker scoped to "/" can take over the whole demos site. Disable it for demos or scope it to this slug.');
  }

  const routerFiles = [];
  let registersWorker = false;
  let absoluteAssets = null;
  for (const [path, data] of files) {
    if (!/^src\/.*\.(jsx?|tsx?)$/.test(path)) continue;
    const code = text(data);
    if (/\b(BrowserRouter|createBrowserRouter)\b/.test(code) && !/basename/.test(code)) routerFiles.push(path);
    if (/serviceWorker\.register/.test(code)) registersWorker = true;
    if (!absoluteAssets) {
      const hit = /["'`(]\/(?:images?|img|assets|fonts?|videos?|icons?|media|photos?)\/[^"'`)\s]+/.exec(code);
      if (hit) absoluteAssets = `${path}: ${hit[0].slice(1)}`;
    }
  }
  if (routerFiles.length) {
    warnings.push(`React Router without a basename in ${routerFiles.join(', ')}. Add basename={import.meta.env.BASE_URL.replace(/\\/$/, "")} or routes will not match.`);
  }
  if (registersWorker) warnings.push('Registers a service worker. Make sure its scope is this demo\'s path, not "/".');
  if (absoluteAssets) {
    warnings.push(`Root-absolute asset path (${absoluteAssets}). Import the file or prefix it with import.meta.env.BASE_URL, or it will 404.`);
  }
  return { pkg, deps, warnings };
}

// Point root-absolute references at /<slug>/ for every top-level entry the zip
// actually contains ("/assets/...", "/favicon.svg"), in text files only.
export function rewriteBuiltBase(files, slug) {
  const indexHtml = text(files.get('index.html'));
  if (indexHtml.includes(`/${slug}/`)) return { files, rewritten: 0 }; // already built for this path

  const tops = [...new Set([...files.keys()].map((p) => p.split('/')[0]))]
    .filter((name) => name !== 'index.html' && name !== 'vercel.json')
    .map((name) => name.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'));
  if (!tops.length) return { files, rewritten: 0 };

  const pattern = new RegExp(`(["'\`(])/(${tops.join('|')})(?=[/"'\`)?#])`, 'g');
  const out = new Map();
  let rewritten = 0;
  for (const [path, data] of files) {
    if (!TEXT_EXT.test(path)) { out.set(path, data); continue; }
    const before = text(data);
    const after = before.replace(pattern, (_, lead, name) => { rewritten += 1; return `${lead}/${slug}/${name}`; });
    out.set(path, after === before ? data : encoder.encode(after));
  }
  return { files: out, rewritten };
}

function builtWarnings(files) {
  const warnings = [];
  for (const [path, data] of files) {
    if (!/\.m?js$/.test(path)) continue;
    const code = text(data);
    if (/history\.pushState|pushState\(/.test(code)) {
      warnings.push('This built site uses client-side routing. It was built for "/", so its routes may not work under the demo path. Upload the source zip instead for a routed app.');
      break;
    }
  }
  for (const [path, data] of files) {
    if (/\.m?js$/.test(path) && /serviceWorker\.register/.test(text(data))) {
      warnings.push('Registers a service worker. A worker scoped to "/" can take over the whole demos site.');
      break;
    }
  }
  return warnings;
}

// Any route that is not a real file serves index.html (refreshes, deep links).
// Merged into an existing vercel.json rather than replacing it.
export function withSpaFallback(files) {
  const out = new Map(files);
  let config = {};
  if (out.has('vercel.json')) {
    try { config = JSON.parse(text(out.get('vercel.json'))); } catch { config = {}; }
  }
  const rewrites = Array.isArray(config.rewrites) ? config.rewrites : [];
  if (!rewrites.some((r) => r?.source === '/(.*)')) rewrites.push({ source: '/(.*)', destination: '/index.html' });
  config.rewrites = rewrites;
  out.set('vercel.json', encoder.encode(JSON.stringify(config, null, 2) + '\n'));
  return out;
}

// Full pipeline: zip bytes in, deployable files plus build settings out.
export function prepareDemo(bytes, slug) {
  const slugError = validateSlug(slug);
  if (slugError) throw new DemoError(slugError);

  let files = stripWrappers(readZip(bytes));
  if (!files.size) throw new DemoError('The zip is empty.');
  const kind = detectKind(files);

  if (kind === 'source') {
    for (const path of [...files.keys()]) {
      if (SOURCE_ONLY_JUNK.some((re) => re.test(path))) files.delete(path);
    }
    let checked;
    try { checked = sourceWarnings(files); } catch { throw new DemoError('package.json is not valid JSON.'); }
    const { pkg, deps, warnings } = checked;
    if (!pkg.scripts?.build) throw new DemoError('package.json has no "build" script.');
    if (!deps.vite) throw new DemoError('This does not look like a Vite project (no "vite" in package.json). Only Vite projects are supported.');

    const env = collectEnv(files);
    for (const name of ENV_FILES) files.delete(name);
    const { command, warning } = buildCommandFor(pkg, slug);
    if (warning) warnings.push(warning);

    return {
      kind,
      files: withSpaFallback(files),
      env,
      warnings,
      settings: { framework: 'vite', installCommand: 'npm install', buildCommand: command, outputDirectory: 'dist' },
    };
  }

  const warnings = builtWarnings(files);
  const rewrite = rewriteBuiltBase(files, slug);
  return {
    kind,
    files: withSpaFallback(rewrite.files),
    env: {},
    warnings,
    rewritten: rewrite.rewritten,
    settings: { framework: null, installCommand: null, buildCommand: null, outputDirectory: null },
  };
}

// Shape the Vercel deployments API expects, plus the bytes to upload per SHA.
export function toVercelFiles(files) {
  const manifest = [];
  const blobs = new Map();
  for (const [file, data] of files) {
    const sha = createHash('sha1').update(data).digest('hex');
    manifest.push({ file, sha, size: data.byteLength });
    blobs.set(sha, data);
  }
  return { manifest, blobs };
}
